language: python
python:
  - "3.4"
install: pip install "Nikola[extras]"
before_script: git remote set-url origin https://${GH_TOKEN}@github.com/ganga-devs/ganga-devs.github.io.git
script: nikola github_deploy

